### ISSUE TITLE
Add tag hacktoberfest

### ISSUE THREAD

**Issue by deusdeditvilar** [matheusfelipeog/fordev#16]
Tô realizando umas atualizações na documentação e adicionando alguns módulos na api, mas teria como adicionar tag do hacktoberfest pra contar o PR, por favor?

**Comment by lordcod99** [comment]
i will do it

**Comment by matheusfelipeog** [comment]
Agradeço pelo interesse em contribuir para o fordev @deusdeditvilar 

Estou iniciando uma grande atualização para a próxima versão. O trabalho está sendo feito na [branch dev](https://github.com/matheusfelipeog/fordev/tree/dev), eu vou mudar e reestruturar muita coisa para melhorar o projeto, então não indico contribuir com código até que essa nova versão seja publicada.

Você pode abrir uma issue descrevendo as ideias que teve para melhorar o projeto e, assim que publicar a nova versão, podemos discutir essas melhorias.
