### ISSUE TITLE
Sugestão: alterar o argumento `state` no README, pois o correto é `uf_code` (segundo o people generator)

### ISSUE THREAD

**Issue by biangomes** [matheusfelipeog/fordev#26]
Opa, tudo bem? Obrigada pelo projeto!

Ao tentar consumir, precisei passar o `state` como argumento, no entanto, foi retornado um `TypeError`.

Consegui contornar, pois vi que o argumento correto é `uf_code`.

Desta forma, estou abrindo essa issue sugerindo a alteração no `README` para atualizar o people generator.

![image](https://user-images.githubusercontent.com/20216893/213610433-a4ca51bb-3149-4f09-97ce-32ee8a724c74.png)

**Comment by matheusfelipeog** [comment]
Olá @biangomes, tudo bem sim e espero que você também.

Muito obrigado por me informar isso, vou fazer a correção.

**Comment by matheusfelipeog** [comment]
Prontinho, corrigido
